---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-12-17a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
