pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts git-buildpackage locales
      - locale-gen --purge en_US.UTF-8
      - mk-build-deps --install -t'apt-get -y'
      - autoreconf -fis
      - ./configure
      - make -j8
      - env LANG="en_US.UTF-8" make check
