Document: omphalos
Title: Debian omphalos Manual
Author: <insert document author here>
Abstract: This manual describes what omphalos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/omphalos/omphalos.sgml.gz

Format: postscript
Files: /usr/share/doc/omphalos/omphalos.ps.gz

Format: text
Files: /usr/share/doc/omphalos/omphalos.text.gz

Format: HTML
Index: /usr/share/doc/omphalos/html/index.html
Files: /usr/share/doc/omphalos/html/*.html
