#!/bin/sh

# Set up a binary to use netlink/packet sockets without being root.
# Requires filesystem-based capabilities (Linux 2.6.24+)

set -e
set -o nounset

usageerr () { echo "usage: `basename $0` executable" ; }
usage () { usageerr >&2 ; return 1 ; }

[ $# -ge 1 ] || usage

if SETCAP="`which setcap`" ; then
	for i in "$@" ; do
		if ! "$SETCAP" "= cap_net_admin,cap_net_raw=ep" "$i" ; then
			echo "The 'setcap' binary failed, using setuid..." >&2
			chown root:root "$i"
			chmod +s "$i"
		fi
	done
else
	echo "Couldn't find the 'setcap' binary, using setuid..." >&2
	for i in "$@" ; do
		chown root:root "$i"
		chmod +s "$i"
	done
fi

