#!/bin/sh

set -e

if ! ulimit -c | grep unlimited > /dev/null ; then
	echo "Warning: need run 'ulimit -c unlimited' to get coredumps!" >&2
fi
echo 1 | sudo tee /proc/sys/fs/suid_dumpable > /dev/null
